version: "3.6"

# Using Docker_BuildKit which requires:
# export DOCKER_BUILDKIT=1
# export COMPOSE_DOCKER_CLI_BUILD=1

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: 3.8

services:
  model-pipeline:
    build: ../model_training_pipeline
    image: ciri_model_pipeline
    container_name: ciri_model_pipeline
    volumes:
      - ./data:/app/data
      - ./secrets:/secrets
    environment:
      - MLFLOW_TRACKING_URI=http://ciri_mlflow:5000/
      - MODEL_NAME=ciri_model
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/ciri-cloud-storage.json
    depends_on:
      - mlflow
    networks:
      - backend

  mlflow:
    restart: always
    build: ../mlflow
    image: ciri_mlflow
    container_name: ciri_mlflow
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/ciri-cloud-storage.json
    volumes:
      - ./db:/db
      - ./secrets:/secrets
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - backend

  api:
    restart: always
    build: ../backend_apis
    container_name: ciri_apis
    ports:
      - "8080:80"
    expose:
      - "80"
    volumes:
      - "../backend_apis:/app"
      - ./secrets:/secrets
    environment:
      - MLFLOW_TRACKING_URI=http://ciri_mlflow:5000/
      - MODEL_NAME=ciri_trashnet_model
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/ciri-cloud-storage.json
    depends_on:
      - mlflow
    networks:
      - frontend
      - backend

  ui:
    restart: always
    build: ../frontend_ui
    container_name: ciri_ui
    ports:
      - "80:8080"
    expose:
      - "8080"
    volumes:
      - "../frontend_ui:/app"
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
