version: "3.6"

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: 3.8

services:
  model-pipeline:
    build: ../model_training_pipeline
    image: ciri_model_pipeline
    container_name: ciri_model_pipeline
    volumes:
      - ./data:/app/data
      - ./artifact-store:/artifact-store
    environment:
      - MLFLOW_TRACKING_URI=http://ciri_mlflow:5000/
      - MODEL_NAME=ciri_model
    depends_on:
      - mlflow
    networks:
      - backend

  mlflow:
    restart: always
    build: ../mlflow
    image: ciri_mlflow
    container_name: ciri_mlflow
    volumes:
      - ./db:/db
      - ./artifact-store:/artifact-store
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - frontend
      - backend

  api:
    restart: always
    build: ../backend_apis
    container_name: ciri_apis
    ports:
      - "80:80"
    expose:
      - "80"
    environment:
      - MLFLOW_TRACKING_URI=http://ciri_mlflow:5000/
      - MODEL_NAME=ciri_model
    depends_on:
      - mlflow
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
