version: "3.6"

# Using Docker_BuildKit which requires:
# export DOCKER_BUILDKIT=1
# export COMPOSE_DOCKER_CLI_BUILD=1

x-build-args:
  &build_args
  INSTALL_PYTHON_VERSION: 3.8

services:
  model-pipeline:
    # build: ../model_training_pipeline
    # image: ciri_model_pipeline
    image: ghcr.io/canirecycleit/model_training_pipeline/ciri_model_pipeline:latest
    container_name: ciri_model_pipeline
    volumes:
      - secret-vol:/secrets
      # - ./data:/app/data
    environment:
      - MLFLOW_TRACKING_URI=http://ciri_mlflow:5000/
      - MODEL_NAME=ciri_model
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/ciri-cloud-storage.json
    depends_on:
      - mlflow
    networks:
      - backend

  mlflow:
    restart: always
    # build: ../mlflow
    # image: ciri_mlflow
    image: ghcr.io/canirecycleit/mlflow/ciri_apis:latest
    container_name: ciri_mlflow
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/ciri-cloud-storage.json
    volumes:
      - db-vol:/db
      - secret-vol:/secrets
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - backend

  api:
    restart: always
    # build: ../backend_apis
    image: ghcr.io/canirecycleit/backend_apis/ciri_apis:latest
    container_name: ciri_apis
    expose:
      - "80"
    volumes:
      - secret-vol:/secrets
    environment:
      - MLFLOW_TRACKING_URI=http://ciri_mlflow:5000/
      - MODEL_NAME=ciri_trashnet_model
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/ciri-cloud-storage.json
    depends_on:
      - mlflow
    networks:
      - frontend
      - backend

  ui:
    restart: always
    # build: ../frontend_ui
    image: ghcr.io/canirecycleit/frontend_ui/ciri_frontend:latest
    container_name: ciri_ui
    expose:
      - "8080"
    # volumes:
    #  - "../frontend_ui:/app"
    networks:
      - frontend

  nginx:
    container_name: ciri_nginx
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - "./conf/nginx/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - frontend
    depends_on:
      - ui
      - api

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  secret-vol: null
  #    driver: local
  #    driver_opts:
  #      type: none
  #      o: bind
  #      device: $PWD/secrets
  db-vol: null

#secrets:
#  google-storage-credentials:
#    file: ./secrets/ciri-cloud-storage.json
