apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mlflow
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mlflow
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: mlflow
    spec:
      containers:
        - env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/ciri-cloud-storage.json
          image: ghcr.io/canirecycleit/mlflow/ciri_apis:latest
          name: ciri-mlflow
          ports:
            - containerPort: 5000
          resources: {}
          volumeMounts:
            - mountPath: /db
              name: db-vol
            - mountPath: /secrets
              name: ciri-cloud-storage
      restartPolicy: Always
      volumes:
        - name: db-vol
          persistentVolumeClaim:
            claimName: db-vol
        - name: ciri-cloud-storage
          secret:
            secretName: ciri-cloud-storage
status: {}
