name: CIRI GKE Deployment

on:
  workflow_dispatch:
  push:
    branches:
    - master

env:
  GKE_CLUSTER: ciri-k8s-cluster
  GKE_ZONE: us-east1-c

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: production
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup gcloud CLI 
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_DEPLOYMENT }}

      - name: Set GKE Credentials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Deploy UI
        run: |-
          k8s_deployment/update_deploy.sh ui
          k8s_deployment/update_deploy.sh mlflow
          k8s_deployment/update_deploy.sh api

      - name: Output Services
        run: |-
          kubectl get services -o wide
          kubectl get services --namespace ingress-nginx