name: CIRI App Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Say Hello
        run:
          echo 'Hello Production environment'